const ALERT = 'ALERT';
const REFETECH_CHATS = 'REFETECH_CHATS';

const NEW_ATTACHMENT = 'NEW_ATTACHMENT';
const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT';

const NEW_MESSAGE = 'NEW_MESSAGE';
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

export { ALERT,NEW_MESSAGE, REFETECH_CHATS,
    START_TYPING, STOP_TYPING, 
     NEW_ATTACHMENT, NEW_MESSAGE_ALERT };